export const dataJson = [
  {
    code: "143",
    name: "北京医院",
    picture: "//img.114yygh.com/image/image-003/23177414396939666.png",
    levelText: "三级甲等",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H01110003",
    name: "中国医学科学院北京协和医院",
    picture: "//img.114yygh.com/image/image-003/33145394063349148.png",
    levelText: "三级甲等",
    openTimeText: "16:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "270",
    name: "中日友好医院",
    picture: "//img.114yygh.com/image/image-003/23178000191187313.png",
    levelText: "三级甲等",
    openTimeText: "16:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H02110003",
    name: "北京大学第一医院",
    picture: "//img.114yygh.com/image/image-003/23176618472499403.png",
    levelText: "三级甲等",
    openTimeText: "18:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "120",
    name: "北京大学人民医院",
    picture: "//img.114yygh.com/image/image-003/23177084467557645.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "142",
    name: "北京大学第三医院",
    picture: "//img.114yygh.com/image/image-003/23176368020632682.png",
    levelText: "三级甲等",
    openTimeText: "12:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "133",
    name: "北京大学口腔医院（魏公村总院)",
    picture: "//img.114yygh.com/image/image-003/23176589027200067.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "127",
    name: "北京大学第六医院",
    picture: "//img.114yygh.com/image/image-003/23176503940541731.png",
    levelText: "三级甲等",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "4",
    name: "中国医学科学院阜外医院",
    picture: "//img.114yygh.com/image/image-003/23176448081185568.png",
    levelText: "三级甲等",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "146",
    name: "中国医学科学院整形外科医院",
    picture: "//img.114yygh.com/image/image-003/23176459715646643.png",
    levelText: "三级甲等",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "3",
    name: "中国医学科学院肿瘤医院",
    picture: "//img.114yygh.com/image/image-003/23176410054422867.png",
    levelText: "三级甲等",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "162",
    name: "解放军总医院第一医学中心（301医院）",
    picture: "//img.114yygh.com/image/image-003/23177271556061774.png",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "114",
    name: "首都医科大学附属北京友谊医院(西城院区)",
    picture: "//img.114yygh.com/image/image-003/23177734184180251.png",
    levelText: "三级甲等",
    openTimeText: "9:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "804",
    name: "首都医科大学附属北京友谊医院(通州院区)",
    picture: "//img.114yygh.com/image/image-003/23177734184180251.png",
    levelText: "三级甲等",
    openTimeText: "9:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "123",
    name: "首都医科大学附属北京同仁医院亦庄院区（南区）",
    picture: "//img.114yygh.com/image/image-003/23176933066768398.png",
    levelText: "三级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "105",
    name: "首都医科大学附属北京同仁医院崇文门院区（东西区）",
    picture: "//img.114yygh.com/image/image-003/23176921733723049.png",
    levelText: "三级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "91",
    name: "首都医科大学附属北京朝阳医院",
    picture: "//img.114yygh.com/image/image-003/23176321688631557.png",
    levelText: "三级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H05110001",
    name: "首都医科大学附属北京朝阳医院石景山院区",
    picture: "//img.114yygh.com/image/image-003/23176321688631557.png",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "103",
    name: "北京大学第四临床医学院北京积水潭医院(新街口院区)",
    picture: "//img.114yygh.com/image/image-003/23176917539099591.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "1169",
    name: "北京大学第四临床医学院北京积水潭医院(新龙泽院区)",
    picture: "//img.114yygh.com/image/image-003/23176917539099591.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "256",
    name: "北京大学第四临床医学院北京积水潭医院(回龙观院区)",
    picture: "//img.114yygh.com/image/image-003/23176946362738148.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H03110001",
    name: "首都医科大学附属北京天坛医院",
    picture: "//img.114yygh.com/image/image-003/23176379889847619.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "108",
    name: "首都医科大学附属北京安贞医院",
    picture: "//img.114yygh.com/image/image-003/23177148062708174.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "106",
    name: "首都医科大学附属北京世纪坛医院（北京铁路总医院）",
    picture: "//img.114yygh.com/image/image-003/23176625589018066.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "113",
    name: "首都医科大学宣武医院",
    picture: "//img.114yygh.com/image/image-003/23177847315489183.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "790",
    name: "北京清华长庚医院",
    picture: "//img.114yygh.com/image/image-003/23176958865063375.png",
    levelText: "三级",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "115",
    name: "首都医科大学附属北京中医医院",
    picture: "//img.114yygh.com/image/image-003/23176941610612494.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H08155001",
    name: "北京肿瘤医院",
    picture: "//img.114yygh.com/image/image-003/30117355765653204.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "34",
    name: "首都医科大学附属北京儿童医院",
    picture: "//img.114yygh.com/image/image-003/23176687826086614.png",
    levelText: "三级甲等",
    openTimeText: "14:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "102",
    name: "首都儿科研究所附属儿童医院",
    picture: "//img.114yygh.com/image/image-003/23176913576264978.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "104",
    name: "首都医科大学附属北京妇产医院北京妇幼保健院东院",
    picture: "//img.114yygh.com/image/image-003/23177745096097977.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "118",
    name: "首都医科大学附属北京妇产医院北京妇幼保健院西院",
    picture: "//img.114yygh.com/image/image-003/23177050950171808.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H01152001B",
    name: "首都医科大学附属北京妇产医院西院直连测试",
    picture: "//img.114yygh.com/image/image-003/23177745096097977.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "109",
    name: "首都医科大学附属北京口腔医院(天坛院区)",
    picture: "//img.114yygh.com/image/image-003/45365652568356195.jpg",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "170",
    name: "首都医科大学附属北京口腔医院(王府井院区)",
    picture: "//img.114yygh.com/image/image-003/45365652568356195.jpg",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "1156",
    name: "首都医科大学附属北京口腔医院（西红门部）",
    picture: "//img.114yygh.com/image/image-003/45365652568356195.jpg",
    levelText: "请选择",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "107",
    name: "首都医科大学附属北京胸科医院",
    picture: "//img.114yygh.com/image/image-003/23176916879721927.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H06154001",
    name: "首都医科大学附属北京佑安医院",
    picture: "//img.114yygh.com/image/image-003/8195044832921241.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "40",
    name: "首都医科大学附属北京地坛医院",
    picture: "//img.114yygh.com/image/image-003/23177453159835277.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H02153001",
    name: "首都医科大学附属北京安定医院",
    picture: "//img.114yygh.com/image/image-003/35498023302602604.png",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "116",
    name: "北京回龙观医院",
    picture: "//img.114yygh.com/image/image-003/23178146374869844.png",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "112",
    name: "北京老年医院",
    picture: "//img.114yygh.com/image/image-003/23177774308651976.png",
    levelText: "三级综合医院",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "117",
    name: "北京小汤山医院",
    picture: "//img.114yygh.com/image/image-003/23177464004872930.png",
    levelText: "三级合格",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H04151001",
    name: "中国中医科学院广安门医院",
    picture: "//img.114yygh.com/image/image-003/23177079347677008.png",
    levelText: "三级甲等",
    openTimeText: "09:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H24151001",
    name: "中国中医科学院广安门医院南区",
    picture: "//img.114yygh.com/image/image-003/23176524245931513.png",
    levelText: "三级甲等",
    openTimeText: "09:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H14152001",
    name: "北京市昌平区妇幼保健院",
    picture: "//img.114yygh.com/image/image-003/23176961937070806.png",
    levelText: "三级",
    openTimeText: "06:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H01110009",
    name: "北京市隆福医院",
    picture: "//img.114yygh.com/image/image-003/23178749520353780.png",
    levelText: "三级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H05110040",
    name: "民航总医院",
    picture: "//img.114yygh.com/image/image-003/23176875181268638.png",
    levelText: "三级",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H08110008",
    name: "航天中心医院",
    picture: "//img.114yygh.com/image/image-003/23176697889298621.png",
    levelText: "三级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H13151001",
    name: "北京中医医院顺义医院",
    picture: "//img.114yygh.com/image/image-003/23176924103321432.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H13110001",
    name: "北京市顺义区医院",
    picture: "//img.114yygh.com/naja/hospital/167.jpg",
    levelText: "三级",
    openTimeText: "17:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H06155001",
    name: "北京博爱医院",
    picture: "//img.114yygh.com/image/image-003/23177178278630564.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H11151001",
    name: "北京中医药大学房山医院",
    picture: "//img.114yygh.com/image/image-003/23177658343814562.png",
    levelText: "三级甲等",
    openTimeText: "22:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "140",
    name: "中国医学科学院阜外医院特需",
    picture: "//img.114yygh.com//image/image-003/23176448081185568.png",
    levelText: "三级甲等",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "145",
    name: "中国人民解放军火箭军特色医学中心",
    picture: "//img.114yygh.com/image/image-003/23177116589343248.png",
    levelText: "三级甲等",
    openTimeText: "0:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H14110001",
    name: "北京市昌平区医院",
    picture: "//img.114yygh.com/image/image-003/27718955688847241.png",
    levelText: "三级",
    openTimeText: "06:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H06151001",
    name: "北京中医药大学东方医院",
    picture: "//img.114yygh.com/image/image-003/23176995706367115.png",
    levelText: "三级甲等",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06151001X",
    name: "北京中医药大学东方医院西院区(二七院区)",
    picture: "//img.114yygh.com/image/image-003/23176995706367115.png",
    levelText: "三级甲等",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06151001N",
    name: "北京中医药大学东方医院经开区院区",
    picture: "//img.114yygh.com/image/image-003/23176951026712449.png",
    levelText: "三级甲等",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H05110007",
    name: "应急管理部应急总医院",
    picture: "//img.114yygh.com/image/image-003/25741002706562018.png",
    levelText: "三级",
    openTimeText: "08:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "253",
    name: "北京丰台右安门医院",
    picture: "//img.114yygh.com/image/image-003/23176840126881016.png",
    levelText: "三级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06110001",
    name: "北京电力医院",
    picture: "//img.114yygh.com/image/image-003/23176658759713612.png",
    levelText: "三级",
    openTimeText: "06:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H12110001",
    name: "首都医科大学附属北京潞河医院",
    picture: "//img.114yygh.com/image/image-003/23176904050447046.png",
    levelText: "三级",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H05110009N",
    name: "北京市垂杨柳医院",
    picture: "//img.114yygh.com/image/image-003/23178014498244655.png",
    levelText: "三级",
    openTimeText: "08:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1154",
    name: "首都医科大学附属北京地坛医院顺义院区",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "129",
    name: "空军特色医学中心",
    picture: "//img.114yygh.com/image/image-003/23177116193528363.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06110005",
    name: "北京航天总医院",
    picture: "//img.114yygh.com/image/image-003/23176599475478781.png",
    levelText: "三级",
    openTimeText: "00:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "128",
    name: "中国人民解放军总医院第三医学中心（武警总医院）",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H05110010",
    name: "航空总医院",
    picture: "//img.114yygh.com/image/image-003/23625164493791069.png",
    levelText: "三级",
    openTimeText: "09:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H05110003",
    name: "战略支援部队特色医学中心（原解放军第306医院）",
    picture: "//img.114yygh.com/image/image-003/23177221873820928.png",
    levelText: "三级甲等",
    openTimeText: "16:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "156",
    name: "中国中医科学院眼科医院",
    picture: "//img.114yygh.com/image/image-003/23176941352360172.png",
    levelText: "三级甲等",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "134",
    name: "中国中医科学院望京医院",
    picture: "//img.114yygh.com//image/image-003/23626216476387006.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1104",
    name: "中国中医科学院望京医院骨伤医疗中心（东直门院区）",
    picture: "//img.114yygh.com//image/image-003/25902765962333941.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "20",
    name: "清华大学玉泉医院（清华大学中西医结合医院）",
    picture: "//img.114yygh.com/image/image-003/23177136229145522.png",
    levelText: "三级中西医结合",
    openTimeText: "8:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "151",
    name: "解放军总医院第四医学中心（304医院）",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1155",
    name: "解放军总医院第五医学中心（原307医院）",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "158",
    name: "解放军总医院第五医学中心（原302医院）",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "125",
    name: "解放军总医院第六医学中心（原海军总医院）",
    picture: "",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "152",
    name: "解放军总医院第七医学中心（陆军总医院）",
    picture: "//img.114yygh.com/image/image-003/35409011732210657.png",
    levelText: "三级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "161",
    name: "解放军总医院第八医学中心(原309医院)",
    picture: "//img.114yygh.com/image/image-003/23177271556061774.png",
    levelText: "三级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "130",
    name: "中国人民解放军联勤保障部队第九八四医院（原二六一医院）",
    picture: "//img.114yygh.com/image/image-003/23177872608922807.png",
    levelText: "三级",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "144",
    name: "解放军305医院",
    picture: "//img.114yygh.com/image/image-003/53290012074172627.jpg",
    levelText: "三级甲等",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "135",
    name: "北京中医药大学东直门医院",
    picture: "//img.114yygh.com/image/image-003/23178096921743099.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "175",
    name: "北京中医药大学东直门医院通州院区",
    picture: "//img.114yygh.com/image/image-003/23177905990706342.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "999",
    name: "北京大望路急诊抢救医院（原北京朝阳急诊抢救中心）",
    picture: "//img.114yygh.com/image/image-003/12770449299602281.png",
    levelText: "三级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "136",
    name: "中国人民武装警察部队北京市总队医院",
    picture: "//img.114yygh.com/image/image-003/23177516482102666.png",
    levelText: "三级甲等",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H08152001",
    name: "北京市海淀区妇幼保健院",
    picture: "//img.114yygh.com/image/image-003/58667094433502035.jpg",
    levelText: "三级",
    openTimeText: "20:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "139",
    name: "北京燕化医院",
    picture: "//img.114yygh.com/image/image-003/23176770613238963.png",
    levelText: "三级",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "154",
    name: "首都医科大学附属复兴医院",
    picture: "//img.114yygh.com/image/image-003/23177196281065898.png",
    levelText: "三级",
    openTimeText: "08:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H051100081",
    name: "北京市第一中西医结合医院（本部）",
    picture: "//img.114yygh.com/image/image-003/23177262314690764.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H051100082",
    name: "北京市第一中西医结合医院（东坝院区）",
    picture: "//img.114yygh.com/image/image-003/23177262314690764.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H051100083",
    name: "北京市第一中西医结合医院（大屯院区）",
    picture: "//img.114yygh.com/image/image-003/23177262314690764.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H24110001",
    name: "北京市大兴区人民医院",
    picture: "//img.114yygh.com/image/image-003/23177010152843547.png",
    levelText: "三级",
    openTimeText: "08:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "155",
    name: "北京京煤集团总医院",
    picture: "//img.114yygh.com/image/image-003/23176928332616223.png",
    levelText: "三级合格",
    openTimeText: "08:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "160",
    name: "北京市宣武中医医院",
    picture: "//img.114yygh.com/image/image-003/23177034345471200.png",
    levelText: "三级乙等",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H112628",
    name: "北京大学国际医院",
    picture: "//img.114yygh.com/image/image-003/23177603439519187.png",
    levelText: "三级",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H24110003",
    name: "北京市大兴区中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/23177645766959777.png",
    levelText: "三级",
    openTimeText: "18:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "230",
    name: "北京市海淀医院",
    picture: "//img.114yygh.com/image/image-003/23176798280532012.png",
    levelText: "三级",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H06110007",
    name: "北京市丰台中西医结合医院",
    picture: null,
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "5",
    name: "北京市大兴区妇幼保健院",
    picture: "//img.114yygh.com/image/image-003/23177056769887972.png",
    levelText: "三级",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "212",
    name: "北京丰台医院",
    picture: "//img.114yygh.com/image/image-003/23176758468717243.png",
    levelText: "三级",
    openTimeText: "08:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "792",
    name: "北京市通州区妇幼保健院",
    picture: "//img.114yygh.com/image/image-003/23176953792839042.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H08151001",
    name: "中国中医科学院西苑医院",
    picture: "//img.114yygh.com/image/image-003/39366983694660483.png",
    levelText: "三级甲等",
    openTimeText: "18:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H14151001",
    name: "北京市昌平区中医医院",
    picture: null,
    levelText: "三级甲等",
    openTimeText: null,
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "229",
    name: "首都医科大学附属北京康复医院(北京工人疗养院)",
    picture: "//img.114yygh.com/image/image-003/23177502780086687.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "124",
    name: "首都医科大学三博脑科医院",
    picture: "//img.114yygh.com/image/image-003/23177779672431445.png",
    levelText: "三级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "241",
    name: "北京市昌平区中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/23176951239046862.png",
    levelText: "三级甲等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1544",
    name: "北京美中爱瑞肿瘤医院",
    picture: "//img.114yygh.com/image/image-003/3531069447106185.png",
    levelText: "三级",
    openTimeText: "09:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H11110003",
    name: "北京市房山区良乡医院",
    picture: null,
    levelText: "三级",
    openTimeText: "20:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "126",
    name: "北京华信医院(清华大学第一附属医院)",
    picture: "//img.114yygh.com/image/image-003/23177858426655220.png",
    levelText: "三级",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1061",
    name: "北京结核病控制研究与防治所",
    picture: "//img.114yygh.com/naja/hospital/1061.jpg",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "150",
    name: "北京大学首钢医院",
    picture: "//img.114yygh.com/image/image-003/23177208327859029.png ",
    levelText: "三级合格",
    openTimeText: "14:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "169",
    name: "北京市鼓楼中医医院",
    picture: "//img.114yygh.com/image/image-003/23177130449305760.png",
    levelText: "三级中医医院",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1060",
    name: "北京市红十字会急诊抢救中心",
    picture: "//img.114yygh.com/image/image-003/27560844400912112.jpg",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H26110001",
    name: "北京市平谷区医院",
    picture: "//img.114yygh.com/image/image-003/23177457014449852.png",
    levelText: "三级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "172",
    name: "北京市平谷区中医医院",
    picture: "//img.114yygh.com/image/image-003/23177171930286991.png",
    levelText: "三级甲等",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "176",
    name: "北京市和平里医院",
    picture: "//img.114yygh.com/image/image-003/23178639021262845.png",
    levelText: "三级甲等",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H04110013",
    name: "北京市健宫医院",
    picture: "//img.114yygh.com/image/image-003/23626858467432002.png",
    levelText: "三级",
    openTimeText: "00:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H04110004",
    name: "北京市回民医院",
    picture: "//img.114yygh.com/image/image-003/31168516172437941.jpg",
    levelText: "三级甲等",
    openTimeText: "09:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "183",
    name: "北京市西城区广外医院（北京市西城区广外老年医院）",
    picture: "//img.114yygh.com/image/image-003/26522295332727381.png",
    levelText: "三级中西医结合",
    openTimeText: "9:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "188",
    name: "北京中医药大学附属护国寺中医医院",
    picture: "//img.114yygh.com/image/image-003/23176694804303583.png",
    levelText: "三级甲等",
    openTimeText: "9:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "208",
    name: "北京市石景山医院",
    picture: "//img.114yygh.com/image/image-003/23177973915751656.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "216",
    name: "北京市朝阳区妇幼保健院（南院区）",
    picture: "//img.114yygh.com/image/image-003/17353871783781009.jpg",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1547",
    name: "北京市朝阳区妇幼保健院（北院区）",
    picture: "//img.114yygh.com/image/image-003/17353871783781009.jpg",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "220",
    name: "北京中医药大学第三附属医院",
    picture: "//img.114yygh.com/image/image-003/23177341772038701.png",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "221",
    name: "北京中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/23178527780020607.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H13152001",
    name: "北京市顺义区妇幼保健院",
    picture: null,
    levelText: "三级",
    openTimeText: "17:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "239",
    name: "北京市肛肠医院（北京市二龙路医院）",
    picture: "//img.114yygh.com/image/image-003/23176689977439027.png",
    levelText: "三级甲等",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06110003",
    name: "中国航天科工集团七三一医院",
    picture: "//img.114yygh.com/image/image-003/31344305515443591.png",
    levelText: "三级",
    openTimeText: "05:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "258",
    name: "首都医科大学宣武医院特需门诊",
    picture: "//img.114yygh.com/naja/hospital/258.jpg",
    levelText: "三级甲等",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H08120008",
    name: "北京四季青医院",
    picture: "//img.114yygh.com/image/image-003/23598595149518207.png",
    levelText: "二级",
    openTimeText: "22:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H09110002",
    name: "北京市门头沟区医院",
    picture: "//img.114yygh.com/image/image-003/1195375088149216.png",
    levelText: "二级甲等",
    openTimeText: "00:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "228",
    name: "北京大学医院",
    picture: "//img.114yygh.com/image/image-003/23178614090210556.png",
    levelText: "二级",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "222",
    name: "北京市密云区医院",
    picture: "//img.114yygh.com/image/image-003/23177144813166784.png",
    levelText: "二级甲等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "225",
    name: "北京市中关村医院",
    picture: "//img.114yygh.com/image/image-003/23176202136883137.png",
    levelText: "二级甲等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "159",
    name: "解放军总医院京东医疗区(原解放军第二六三医院)",
    picture: "//img.114yygh.com/image/image-003/23177293047912002.png",
    levelText: "二级甲等",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H06159071",
    name: "北京市丰台区妇幼保健计划生育服务中心（北京市丰台区妇幼保健院）",
    picture: "//img.114yygh.com/image/image-003/23176324388504164.png",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "185",
    name: "北京市第二医院",
    picture: "//img.114yygh.com/image/image-003/23177306912160708.png",
    levelText: "二级甲等综合医院",
    openTimeText: "09:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "178",
    name: "北京市第六医院",
    picture: "//img.114yygh.com/image/image-003/23176657456570527.png",
    levelText: "二级甲等",
    openTimeText: "9:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "H12110003",
    name: "北京市通州区中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/23176545513281257.png",
    levelText: "二级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H12110003b",
    name: "北京市通州区中西医结合医院宋庄院区（骨伤医院宋庄院区）",
    picture: "//img.114yygh.com/image/image-003/23176545513281257.png",
    levelText: "二级甲等",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "9",
    name: "北京市仁和医院",
    picture: "//img.114yygh.com/image/image-003/23176234427153519.png",
    levelText: "二级甲等",
    openTimeText: "0:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "218",
    name: "北京市丰台区中医医院（南苑医院）",
    picture: "//img.114yygh.com/image/image-003/23177366704926191.png",
    levelText: "二级乙等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "219",
    name: "北京市丰台康复医院（北京市丰台区铁营医院）",
    picture: "//img.114yygh.com/image/image-003/23178480550806908.png",
    levelText: "二级乙等",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "226",
    name: "清华大学医院",
    picture: "",
    levelText: "二级",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "233",
    name: "北京市昌平区南口医院",
    picture: "//img.114yygh.com/image/image-003/23176842958970319.png",
    levelText: "二级乙等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "238",
    name: "北京市昌平区南口铁路医院",
    picture: "//img.114yygh.com/image/image-003/23176876607853681.png",
    levelText: "二级乙等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "237",
    name: "北京市昌平区沙河医院",
    picture: "//img.114yygh.com/image/image-003/23177077420475949.png",
    levelText: "二级医院",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "242",
    name: "北京市昌平区精神卫生保健院",
    picture: "//img.114yygh.com/image/image-003/23177543488077218.png",
    levelText: "二级",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "8",
    name: "北京普祥中医肿瘤医院",
    picture: "//img.114yygh.com/image/image-003/23177087353283320.png",
    levelText: "二级医院",
    openTimeText: "0:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "11",
    name: "北京市大兴区心康医院(原大兴区精神病医院)",
    picture: "//img.114yygh.com/image/image-003/23177691097451043.png",
    levelText: "二级甲等",
    openTimeText: "09:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H40102867X",
    name: "北京市延庆区医院（北京大学第三医院延庆医院）",
    picture: "//img.114yygh.com/image/image-003/23176751245947414.png",
    levelText: "二级甲等",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "165",
    name: "北京怀柔医院",
    picture: "//img.114yygh.com/image/image-003/23178058864323712.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "168",
    name: "北京市东城区妇幼保健计划生育服务中心（北京市东城区妇幼保健院南院区）",
    picture: "//img.114yygh.com/image/image-003/23178036620272449.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "171",
    name: "北京市顺义区空港医院",
    picture: "//img.114yygh.com/image/image-003/23176661736575361.png",
    levelText: "二级医院",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1029",
    name: "北京按摩医院",
    picture: "//img.114yygh.com/image/image-003/23176259864298982.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1030",
    name: "北京市丰盛中医骨伤专科医院",
    picture: "//img.114yygh.com/image/image-003/23176481122204364.png",
    levelText: "二级甲等",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1032",
    name: "国家康复辅具研究中心附属康复医院",
    picture: "//img.114yygh.com/image/image-003/23176972944765414.png",
    levelText: "二级合格",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1053",
    name: "兵器工业北京北方医院",
    picture: "//img.114yygh.com/image/image-003/23176968044722336.png",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1069",
    name: "北京市顺义区精神病医院",
    picture: "",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1021",
    name: "北京市丰台区心理卫生中心（原精神卫生防治院）",
    picture: "",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "177",
    name: "北京市普仁医院",
    picture: "//img.114yygh.com//image/image-003/23626824178149754.png",
    levelText: "二级甲等",
    openTimeText: "9:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "180",
    name: "北京市东城区第一人民医院",
    picture: "//img.114yygh.com/image/image-003/23177323300738135.png",
    levelText: "二级甲等中医医院",
    openTimeText: "9:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "182",
    name: "北京市门头沟区中医医院（北京市门头沟区老年病医院）",
    picture: "//img.114yygh.com/image/image-003/23177405720565120.png",
    levelText: "二级甲等",
    openTimeText: "9:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H02110010",
    name: "北京市西城区展览路医院",
    picture: "//img.114yygh.com/image/image-003/23177613935824070.png",
    levelText: "二级",
    openTimeText: "15:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "190",
    name: "北京市房山区第一医院",
    picture: "//img.114yygh.com/image/image-003/23177924272120296.png",
    levelText: "二级甲等",
    openTimeText: "20:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "203",
    name: "北京核工业医院（原房山401医院）",
    picture: "//img.114yygh.com/image/image-003/23177056414411123.png",
    levelText: "二级甲等",
    openTimeText: "09:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "204",
    name: "北京市上地医院",
    picture: "//img.114yygh.com//image/image-003/23626832797132645.png",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "205",
    name: "北京市朝阳区中医医院",
    picture: "//img.114yygh.com/image/image-003/23178392031227395.png",
    levelText: "二级甲等",
    openTimeText: "09:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: true,
  },
  {
    code: "206",
    name: "北京市怀柔区中医医院",
    picture: "//img.114yygh.com/image/image-003/23178430822995329.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "207",
    name: "北京市朝阳区双桥医院",
    picture: "//img.114yygh.com/image/image-003/23177441747689361.png",
    levelText: "二级",
    openTimeText: "09:45",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "217",
    name: "北京市密云区中医医院",
    picture: "//img.114yygh.com//image/image-003/23626621962912779.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "227",
    name: "北京水利医院",
    picture: "//img.114yygh.com/image/image-003/23177434785924892.png",
    levelText: "二级甲等",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "232",
    name: "北京中医医院延庆医院",
    picture: "//img.114yygh.com/image/image-003/23177182457187149.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "234",
    name: "北京市石景山区中医医院",
    picture: "//img.114yygh.com/image/image-003/23178682703929501.png",
    levelText: "二级合格",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "249",
    name: "北京市社会福利医院",
    picture: "",
    levelText: "二级甲等",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "275",
    name: "北京市东城区妇幼保健计划生育服务中心（北京市东城区妇幼保健院北院区）",
    picture: "//img.114yygh.com/image/image-003/23177381949988361.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H08110013",
    name: "北京市化工职业病防治院（北京市职业病防治研究院）",
    picture: "//img.114yygh.com/image/image-003/3096336471186096.png",
    levelText: "二级甲等",
    openTimeText: "18:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H04152001",
    name: "北京市西城区妇幼保健计划生育服务中心（北京市西城区妇幼保健院）",
    picture: "//img.114yygh.com/image/image-003/27199299121996582.jpg",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "215",
    name: "北京惠民中医儿童医院",
    picture: "",
    levelText: "一级专科",
    openTimeText: "10:15",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "797",
    name: "北京市西城区德胜社区卫生服务中心",
    picture: "//img.114yygh.com/naja/hospital/797.jpg",
    levelText: "一级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1049",
    name: "北京爱尔英智眼科医院",
    picture: "//img.114yygh.com/image/image-003/42072976178829933.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H21151415",
    name: "北京京都儿童医院",
    picture: "//img.114yygh.com/image/image-003/12582266502030334.jpg",
    levelText: "三级",
    openTimeText: "17:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1028",
    name: "北京朝阳中西医结合急诊抢救医院",
    picture: "//img.114yygh.com/image/image-003/23176445625509602.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1051",
    name: "北京马应龙长青肛肠医院",
    picture: "//img.114yygh.com/naja/hospital/1051.jpg",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1112",
    name: "北京爱育华妇儿医院",
    picture: "//img.114yygh.com/image/image-004/23177641978535914.png",
    levelText: "三级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1114",
    name: "北京国丹白癜风医院",
    picture: "//img.114yygh.com/image/image-004/23177771651843892.png",
    levelText: "三级",
    openTimeText: "07:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1115",
    name: "北京美尔目第二眼科医院",
    picture: "",
    levelText: "三级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1052",
    name: "北京北亚骨科医院",
    picture: "//img.114yygh.com/image/image-004/23178093541631597.png",
    levelText: "三级",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1059",
    name: "北京北大医疗康复医院",
    picture: "//img.114yygh.com/image/image-004/23177567045941940.png",
    levelText: "三级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1017",
    name: "北京王府中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/23177809325680833.png",
    levelText: "三级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1132",
    name: "北京中科白癜风医院",
    picture: "//img.114yygh.com/image/image-003/35409526814847281.png",
    levelText: "三级",
    openTimeText: "7:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H07151051",
    name: "北京联科中医肾病医院",
    picture: "//img.114yygh.com/image/image-004/23178019026817828.png",
    levelText: "三级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1146",
    name: "北京京城皮肤病医院",
    picture: "//img.114yygh.com/image/image-004/23177725368819750.png",
    levelText: "请选择",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1153",
    name: "北京裕和中西医结合康复医院",
    picture: "//img.114yygh.com/image/image-004/23177277180555704.png",
    levelText: "三级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1148",
    name: "北京首大眼耳鼻喉医院",
    picture: "//img.114yygh.com/image/image-004/23178193091906642.png",
    levelText: "三级合格",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1147",
    name: "北京中诺口腔医院",
    picture: "//img.114yygh.com/image/image-004/25232756936631738.png",
    levelText: "三级",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H10002301",
    name: "北京扶正肿瘤医院",
    picture: "//img.114yygh.com/image/image-003/26589205593142527.png",
    levelText: "三级",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1015",
    name: "北京百子湾和美妇儿医院",
    picture: "//img.114yygh.com/naja/hospital/1015.jpg",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1012",
    name: "北京市朝阳区三环肿瘤医院",
    picture: "//img.114yygh.com/naja/hospital/1012.jpg",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1033",
    name: "北京保法肿瘤医院",
    picture: "//img.114yygh.com/naja/hospital/1033.jpg",
    levelText: "二级",
    openTimeText: "11:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1027",
    name: "北京军颐中医医院",
    picture: "//img.114yygh.com/naja/hospital/1027.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1043",
    name: "北京新华卓越康复医院",
    picture: "//img.114yygh.com/naja/hospital/1043.jpg",
    levelText: "二级乙等",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1042",
    name: "北京安娜贝儿妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1042.jpg",
    levelText: "二级",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1038",
    name: "北京市朝阳区桓兴肿瘤医院",
    picture: "//img.114yygh.com/naja/hospital/1038.jpg",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1035",
    name: "北京太和妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1035.jpg",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1048",
    name: "北京皇城股骨头坏死专科医院",
    picture: "//img.114yygh.com/naja/hospital/1048.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1056",
    name: "北京精诚博爱康复医院",
    picture: "//img.114yygh.com/naja/hospital/1056.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1076",
    name: "北京先宝妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1076.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1075",
    name: "北京高博博仁医院",
    picture: "//img.114yygh.com/naja/hospital/1075.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1072",
    name: "北京南郊肿瘤医院",
    picture: "//img.114yygh.com/naja/hospital/1072.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1068",
    name: "北京侯丽萍风湿病中医医院",
    picture: "//img.114yygh.com/naja/hospital/1068.jpg",
    levelText: "二级",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1067",
    name: "北京年轮中医骨科医院",
    picture: "//img.114yygh.com/naja/hospital/1067.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1080",
    name: "北京优联眼耳鼻喉医院",
    picture: "//img.114yygh.com/naja/hospital/1080.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1088",
    name: "北京万柳美中宜和妇儿医院",
    picture: "//img.114yygh.com/naja/hospital/1088.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1085",
    name: "北京德尔康尼骨科医院",
    picture: "//img.114yygh.com/naja/hospital/1085.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1084",
    name: "北京安琪妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1084.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1083",
    name: "北京汉琨中医医院",
    picture: "//img.114yygh.com/naja/hospital/1083.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1082",
    name: "北京龙山中医医院",
    picture: "//img.114yygh.com/naja/hospital/1082.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1081",
    name: "北京国济中医医院",
    picture: "//img.114yygh.com/naja/hospital/1081.jpg",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1079",
    name: "北京俪婴妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1079.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1091",
    name: "北京圣宝妇产医院",
    picture: "//img.114yygh.com/naja/hospital/1091.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1098",
    name: "北京光熙康复医院",
    picture: "//img.114yygh.com/naja/hospital/1098.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1094",
    name: "北京和美妇儿医院",
    picture: "//img.114yygh.com/naja/hospital/1094.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1093",
    name: "北京亚运村美中宜和妇儿医院",
    picture: "//img.114yygh.com/naja/hospital/1093.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1092",
    name: "北京美中宜和妇儿医院",
    picture: "//img.114yygh.com/naja/hospital/1092.jpg",
    levelText: "二级合格",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1089",
    name: "北京康益德中西医结合肺科医院",
    picture: "//img.114yygh.com/image/image-003/2845770642599358.png",
    levelText: "二级甲等",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "H03151022",
    name: "北京同仁堂中医医院",
    picture: "//img.114yygh.com/image/image-003/47847226921704624.jpg",
    levelText: "二级",
    openTimeText: "08:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1039",
    name: "北京京顺医院",
    picture: "//img.114yygh.com/image/image-004/23177916125570157.png",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1110",
    name: "北京圣马克医院",
    picture: "//img.114yygh.com/image/image-004/23178232916371152.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1111",
    name: "北京弘和妇产医院",
    picture: "//img.114yygh.com/image/image-004/23177866995346380.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1113",
    name: "北京和睦家康复医院",
    picture: "",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1116",
    name: "北京麦瑞骨科医院",
    picture: "//img.114yygh.com/image/image-004/23178070120817973.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1117",
    name: "北京丰台建都中西医结合医院",
    picture: "//img.114yygh.com/image-004/23177753952275645.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1119",
    name: "北京家恩德仁医院",
    picture: "",
    levelText: "二级甲等",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1118",
    name: "北京瑞安康复医院",
    picture: "",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1120",
    name: "北京强寿中医医院",
    picture: "//img.114yygh.com/image/image-004/23178190978778454.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1121",
    name: "北京京北健永口腔医院",
    picture: "",
    levelText: "二级乙等",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1122",
    name: "北京市平谷区京东口腔医院",
    picture: "//img.114yygh.com/image/image-003/33356511172229253.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1123",
    name: "北京嫣然天使儿童医院",
    picture: "//img.114yygh.com/image/image-004/23177333681334092.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1124",
    name: "北京大兴兴业口腔医院",
    picture: "//img.114yygh.com/image/image-003/34222006998843502.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1125",
    name: "北京永林口腔医院",
    picture: "//img.114yygh.com/naja/hospital/HFG001180.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1126",
    name: "北京市海淀区同步中医骨科医院",
    picture: "//img.114yygh.com/image/image-004/26016757589138643.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1127",
    name: "北京家圆医院",
    picture: "//img.114yygh.com/image/image-003/8436216285802370.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1128",
    name: "北京同安骨科医院",
    picture: "//img.114yygh.com/image/image-003/33760213215132693.png",
    levelText: "二级",
    openTimeText: "06:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1073",
    name: "北京市红十字会和平骨科医院",
    picture: "//img.114yygh.com/image/image-003/47067928184877883.jpg",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1130",
    name: "北京希玛林顺潮眼科医院",
    picture: "//img.114yygh.com/image/image-004/23177633006615247.png",
    levelText: "二级合格",
    openTimeText: "11:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1131",
    name: "北京凤凰妇儿医院",
    picture: "//img.114yygh.com/image/image-004/23178141815076762.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1133",
    name: "瑞泰口腔医院-总院（朝阳区）",
    picture: "",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1134",
    name: "瑞泰口腔医院丰台分院",
    picture: "",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1135",
    name: "北京美中宜和北三环妇儿医院",
    picture: "//img.114yygh.com/image/image-003/31179150738147694.jpg",
    levelText: "二级",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1136",
    name: "北京五洲妇儿医院",
    picture: "",
    levelText: "二级合格",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1138",
    name: "北京和平里中西医结合医院",
    picture: "//img.114yygh.com/image/image-003/2845541942708800.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1139",
    name: "北京嘉禾妇儿医院",
    picture: "//img.114yygh.com/image/image-004/23178205204629777.png",
    levelText: "二级",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1140",
    name: "北京极简一站式口腔医院",
    picture: "//img.114yygh.com/image/image-004/7744879441153218.png",
    levelText: "二级",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1141",
    name: "北京优颐口腔医院",
    picture: "//img.114yygh.com/image/image-004/25413242048379727.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1142",
    name: "北京泰康拜博口腔医院（总院）",
    picture: "//img.114yygh.com/image/image-003/33680722089314040.jpg",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1143",
    name: "中科领军北京口腔医院",
    picture: "//img.114yygh.com/image/image-004/24197814375872757.png",
    levelText: "二级",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1144",
    name: "北京维尔海淀口腔医院",
    picture: "//img.114yygh.com/image/image-002/25324161747093085.png",
    levelText: "二级",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1149",
    name: "北京和睦家医院",
    picture: "//img.114yygh.com/image/image-004/23619264406506935.png",
    levelText: "二级合格",
    openTimeText: "10:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1150",
    name: "北京四惠中医医院",
    picture: "//img.114yygh.com/image/image-003/9662022848036505.png",
    levelText: "二级",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1151",
    name: "北京华医中西医结合皮肤病医院",
    picture: "//img.114yygh.com/image/image-004/23177462338747592.png",
    levelText: "二级甲等",
    openTimeText: "8:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1145",
    name: "北京中诺第二口腔医院",
    picture: "//img.114yygh.com/image/image-003/31285181447466293.jpg",
    levelText: "二级",
    openTimeText: "8:30",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1106",
    name: "北京华诺奥美医学检验实验室",
    picture: "//img.114yygh.com/image/image-003/28012310010356286.png",
    levelText: "请选择",
    openTimeText: "00:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1107",
    name: "北京安诺优达医学检验实验室有限公司",
    picture: "//img.114yygh.com/image/image-003/28012289116266207.png",
    levelText: "请选择",
    openTimeText: "07:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1109",
    name: "北京华大医学检验所有限公司",
    picture: "",
    levelText: "检测机构",
    openTimeText: "7:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
  {
    code: "1108",
    name: "北京博奥医学检验所有限公司",
    picture: "//img.114yygh.com/image/image-003/28012300338745994.png",
    levelText: "检测机构",
    openTimeText: "10:00",
    maintain: false,
    distance: null,
    coordinate: null,
    showRegister: true,
    showPay: false,
    showQuery: false,
  },
];
